### PR TITLE
Openfire 5.0.0 compatibility

### LINKED ISSUE #392: openfire 4.10: java.lang.NoSuchMethodError:  org.jivesoftware.openfire.muc.MUCRoom.getAffiliation(org.xmpp.packet.JID)
Logged whilst trying to use openfire 4.10
```
2024.10.18 15:56:10 ESC[1;31mERRORESC[m [socket_c2s-thread-4]: org.jivesoftware.openfire.nio.NettyConnectionHandler - Closing connection on /2a05:d014:12f0:9703:e77d:1950:a7d4:cb0d:5222
--/2a10:3781:420d:1:c9a3:467:be50:1f29:38170 due to error while processing message: <iq type="set" id="s1VmF5tBve4H" from="guus.der.kinderen@igniterealtime.org/Conversations.-fgD" to="x
mppnetworkgraph@conference.igniterealtime.org" xmlns="jabber:client"><query queryid="c3hjur06uj" xmlns="urn:xmpp:mam:2"><x type="submit" xmlns="jabber:x:data"><field var="FORM_TYPE" typ
e="hidden"><value>urn:xmpp:mam:2</value></field><field var="start"><value>2024-09-23T19:40:31.074Z</value></field><field var="end"><value>2024-10-13T15:56:11.606Z</value></field></x><se
t xmlns="http://jabber.org/protocol/rsm"><before/><max>50</max></set></query></iq>
java.lang.NoSuchMethodError: 'org.jivesoftware.openfire.muc.MUCRole$Affiliation org.jivesoftware.openfire.muc.MUCRoom.getAffiliation(org.xmpp.packet.JID)'
        at com.reucon.openfire.plugin.archive.xep0313.IQQueryHandler.handleIQ(IQQueryHandler.java:181) ~[?:?]
        at org.jivesoftware.openfire.muc.spi.MultiUserChatServiceImpl.process(MultiUserChatServiceImpl.java:504) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.muc.spi.MultiUserChatServiceImpl.processPacket(MultiUserChatServiceImpl.java:375) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.component.InternalComponentManager$RoutableComponents.process(InternalComponentManager.java:864) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.spi.RoutingTableImpl.routeToComponent(RoutingTableImpl.java:516) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.spi.RoutingTableImpl.routePacket(RoutingTableImpl.java:331) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.IQRouter.handle(IQRouter.java:352) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
        at org.jivesoftware.openfire.IQRouter.route(IQRouter.java:106) ~[xmppserver-4.10.0-SNAPSHOT.jar:4.10.0-SNAPSHOT]
...
```

### PR DESCRIPTION
**Pull request by guusdk**
Fixes compatibility issue with Openfire 4.10.0. This plugin now requires 4.10.0 (it is not compatible with earlier versions of Openfire).

The build depends on a snapshot build of 4.10.0, which isn't ideal. At the time of writing, there's no stable release of that version yet.

fixes #392

### CODE REVIEW

**Comment by hqv126** [comment]
Is there anything preventing the changes in this PR from being accepted and merged? I have some Jetty 12 EE8 changes that I can include in another PR once this one is approved.

**Comment by Fishbowler** [comment]
Hi Huy 👋

Whilst I don't _think_ there's anything blocking it, we'd definitely want to be sure that we don't want another 4.9.x compatible plugin release first.

**Comment by Fishbowler** [comment]
To what extent has anyone been able to test this so far?

**Comment by hqv126** [comment]
@guusdk Should I complete the work you've done in this plugin to make it fully compatible with version Openfire 5.0.0? Testing can then be carried out afterwards.

**Comment by guusdk** [comment]
@Fishbowler I believe I've tested it somewhat, but I don't recall to what extent. We will be modifying this plugin in the near future considerably, so a lot of implicit testing will happen anyway.

We're well on our way to a 5.0.0 release. Holding back this change in anticipation of more 4.9.x-compatible releases is starting to hold us back. I'll merge this, to make ongoing development efforts easier.

**Comment by guusdk** [comment]
@hqv126 Now that these changes are merged, you should be able to add your new improvements as a new branch of the (updated) HEAD of the Main branch.

**Pull request merged**
