### PR TITLE
fix issue #19

### PR DESCRIPTION
**Pull request by momone83**

### CODE REVIEW

**Comment by guusdk** [comment]
Exactly what issue does this intend to fix? I do not understand how #19 ("unable to reconstruct stanza") applies to clustering. Are these two distinct issues (that have been logged in the same JIRA tracker?).

It feels wrong to send the both the stanza as well as the body (which is part of the stanza) in the cluster event.

**Comment by momone83** [comment]
Hi.

JIRA ISSUE DESCRIPTION:
When an archived message does not contain a stanza, but does contain body data, the monitoring plugin attempts to reconstruct the stanza. A string formatter is used here, but uses invalid parameters. This results in a stanza that contains placeholders, rather than actual data.

Like I wrote in
https://github.com/igniterealtime/openfire-monitoring-plugin/issues/19#issuecomment-473969465

debugging code, I’ve found that plugin doesn’t reconstruct stanza (for retrivial needs like MAM) because stanza field in database doesn’t exist. This appens (empty field) in cluster configuration, when a junior node receives message and try to store it to database.

This is the code indicted, the same I’ve comment in issue #19:

I hope I made myself clear.
Thanks.

**Comment by momone83** [comment]
To understand what I mean, try to send a message to a junior node in a cluster. After that try to fetch this message from client (using MAM specifications). You’ll find that the massage you’ve sent will never returned.
This happens because of the empty stanza field in database.

**Comment by momone83** [comment]
Hi, any news?

**Comment by momone83** [comment]
Hi, I’d like to know if you tested what I described in previous comments. Have you tried to interact with junior nodes of a cluster configuration? Please let me know if you have some news. I’ve fixed this problem for our Openfire cluster, as in pull request, but we would like to install new versions of Monitoring plugin (to use mam:2) and the problem is still present. Thank you.

**Comment by abdurrahmanekr** [comment]
Hello, i have same problem, and this PR fixed this issue. Please merge this PR @guusdk

**Comment by abdurrahmanekr** [comment]
Hi @momone83, I tried your solution, but it didn't work. I've been trying to get him to work for a week. I didn't notice two methods (writeExternal and readExternal) in ConversationEvent.java.
And when I add the following code, your solution works.

```diff
public class ConversationEvent implements Externalizable {
    ...
    public void writeExternal(ObjectOutput out) throws IOException {
        ...
+        ExternalizableUtil.getInstance().writeBoolean(out, stanza != null);
+        if (stanza != null) {
+            ExternalizableUtil.getInstance().writeSafeUTF(out, stanza);
+        }
    }

    ...
    public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
        ...
+        if (ExternalizableUtil.getInstance().readBoolean(in)) {
+            stanza = ExternalizableUtil.getInstance().readSafeUTF(in);
+        }
    }
    ...
}
```

Hi @guusdk , I see this PR as a solution. If we do not merge this PR, messages (so stanzas) chatting on junior nodes will not be added to the database.

**Comment by guusdk** [comment]
Hi guys. Thanks for explaining it to me - it makes sense. What's up with the suggestion that was made by @abdurrahmanekr ? Do, or don't we need this?

**Comment by momone83** [comment]
HI @abdurrahmanekr, you are right. For some reason I have that snippets of code in master branch but not in the pull request branch. I'm fixing that and I'll push my update asap.

**Comment by momone83** [comment]
Hi @guusdk I'm going to push a new fixed version. Just a note: This fix is ​​valid for all versions after 1.7.0
Thanks.

**Comment by momone83** [comment]
Hi @guusdk I'm going to push a new fixed version. Just a note: This fix is ​​valid for all versions after 1.7.0
Thanks.

**Comment by abdurrahmanekr** [comment]
Hello @guusdk, are there any updates?

**Comment by momone83** [comment]
Hi Gus, are there any updates?
May I ask why a major issue like this has been completely ignored for over a year?
Thanks.

**Comment by guusdk** [comment]
I'm sorry that this is taking so long. Please understand that the time spent on issues like these is time that comes out of free time from volunteers, that prioritize work according to their availability, needs, and preferences.

**Comment by akrherz** [comment]
Repository has been rewritten, #129 covers this one.

**Pull request closed without merging**
