### PR TITLE
fix issues #48 and #72, improve performance

### PR DESCRIPTION
**Pull request by koledas**
- Fix Issues igniterealtime#48 and igniterealtime#72.
- Improve performance load conversations (tested on PostgreSQL 11.7, size of DB 7Gb. Client Vacuum-IM 1.3.0.)

### CODE REVIEW

**Comment by DavisR-GitHub** [comment]
Why nobody merges this request

**Comment by guusdk** [comment]
The change in this PR is rather large, and addresses more than one issue. This makes reviewing more complex. It is generally preferable to create distinct, concise PRs, as that will help reviewers process things faster.

It's understandable that PRs that take a long time to be reviewed can be frustrating. Please do remember that the community consists of volunteers, that sometimes have other priorities.

**Comment by DavisR-GitHub** [comment]
@koledas,
May be you could split this request into several small requests?
We really need in these fixes.

**Comment by koledas** [comment]
@DavisR-GitHub 
Sorry, but why is there such a rush?
You can use this plugin: https://github.com/igniterealtime/openfire-monitoring-plugin/files/4387326/monitoring.zip
And my fork: https://github.com/koledas/openfire-monitoring-plugin
Now it’s hard to remember which change related to which problem. In the future I will create distinct, concise PRs.

**Comment by DavisR-GitHub** [comment]
Rush?
Pull request was created 3 month ago and still even did not reviewed...

**Comment by guusdk** [comment]
#72 is now fixed in https://github.com/igniterealtime/openfire-monitoring-plugin/pull/123

**Comment by akrherz** [comment]
Sorry, this PR will need to be resubmitted, I was not able to fix it after the repository rewrite to remove [unrelated commits](https://discourse.igniterealtime.org/t/89049).

**Pull request closed without merging**
