### PR TITLE
Adding support for private MUC messages to MAM

### PR DESCRIPTION
**Pull request by guusdk**

### CODE REVIEW

**Comment by guusdk** [comment]
I've now rebased this to take in @akrherz's work with moving to Github Actions (see #149)

**Comment by guusdk** [comment]
This branch is currently largely finished, with the notable exception of Lucene. That needs to be modified to work with private messages.

**Comment by Fishbowler** [comment]
Issue: **DMs are recorded twice in the database**

Setup:
- Using [Openfire Docker Compose](https://github.com/surevine/openfire-docker-compose) in clustered mode
- 3 users connected (user 1 to node 1, user 2 & 3 to node 2)
- Everyone joins MUC2
- Everyone sends a message each to the MUC
- User1 sends a DM to User2
- User2 sends a DM to User3
- User1 sends one more message to the open MUC

When looking at the ofMessageArchive table, the MUC messages are stored once, but the DMs are stored twice with slightly different information in some columns, but the same stanzas.

image

**Comment by Fishbowler** [comment]
Issue: Using RSM "after" gets no results and only a count.

Setup: As above

Steps:
- Send the following stanza, where the `after` is the stanza-id of the 3rd MUC message. Depending on the user, this should include either 1 or 2 DMs plus 1 MUC message.
```
<iq to="muc2@conference.xmpp.localhost.example" id="dantest1" type="set">
    <query xmlns='urn:xmpp:mam:2' queryid='00003'>
        <x xmlns='jabber:x:data' type='submit'>
            <field var='FORM_TYPE'>
                <value>urn:xmpp:mam:2</value>
            </field>
        </x>
        <set xmlns='http://jabber.org/protocol/rsm'>
            <max>100</max>
            <after>4742b839-11ba-4d1c-af90-30a203ac7e41</after>
        </set>
    </query>
</iq>
```
- See the following returned:
```
<iq type="result" id="dantest1" from="muc2@conference.xmpp.localhost.example" to="user3@xmpp.localhost.example/DaCa000346.local">
    <fin xmlns="urn:xmpp:mam:2" queryid="00003" complete="true">
        <set xmlns="http://jabber.org/protocol/rsm">
            <count>5</count>
        </set>
    </fin>
</iq>
```
I assume that the reason this is 5 and not 3 is because of the bug above.
Modifying the Max value (or omitting it) in the query does not modify the result.

**Comment by Fishbowler** [comment]
Issue: *The storage of DMs is inconsistent*

Setup: as above

Steps: None

Looking at the data stored in ofMessageArchive, there's an inconsistency in the data written to the archive.
Looking at the 2 DMs sent, the stored stanzas are different in that the 2nd message has the "to" attribute translated from roomJID to realJID.
All 3 users were using identical clients, so the only difference I can see is that the first DM (the one I think is correct) is the only one to cross the cluster.

DM from User 1 to User 2
------------------------

## Sent from user1's client:

```
<message to='muc2@conference.xmpp.localhost.example/user2' id='66B4d-149' type='chat'>
  <thread>W4tZyF</thread>
  <x xmlns='http://jabber.org/protocol/muc#user'></x>
  <body>Whisper 1 to 2</body>
  <x xmlns="jabber:x:event">
    <offline/>
    <composing/>
  </x>
  <active xmlns='http://jabber.org/protocol/chatstates'/>
</message>
```

## Stored in the archive:

```
<message xmlns="jabber:client" to="muc2@conference.xmpp.localhost.example/user2" id="66B4d-149" type="chat" from="muc2@conference.xmpp.localhost.example/user1">
    <thread>W4tZyF</thread>
    <x xmlns="http://jabber.org/protocol/muc#user"></x>
    <body>Whisper 1 to 2</body>
    <x xmlns="jabber:x:event">
        <offline/>
        <composing/>
    </x>
    <active xmlns="http://jabber.org/protocol/chatstates"></active>
    <stanza-id xmlns="urn:xmpp:sid:0" id="48e68c9a-8f29-4fdb-afa5-3693512f6398" by="muc2@conference.xmpp.localhost.example"></stanza-id>
    <addresses xmlns="http://jabber.org/protocol/address">
        <address type="ofrom" jid="user1@xmpp.localhost.example"/>
    </addresses>
</message>
```

DM from User 2 to User 3
------------------------

## Sent from user2's client:

```
<message to='muc2@conference.xmpp.localhost.example/user3' id='963bH-151' type='chat'>
  <thread>inJ2hF</thread>
  <x xmlns='http://jabber.org/protocol/muc#user'></x>
  <body>Whisper 2 to 3</body>
  <x xmlns="jabber:x:event">
    <offline/>
    <composing/>
  </x>
  <active xmlns='http://jabber.org/protocol/chatstates'/>
</message>
```

## Stored in the archive:

```
<message xmlns="jabber:client" to="user3@xmpp.localhost.example/DaCa000346.local" id="963bH-151" type="chat" from="muc2@conference.xmpp.localhost.example/user2">
    <thread>inJ2hF</thread>
    <x xmlns="http://jabber.org/protocol/muc#user"></x>
    <body>Whisper 2 to 3</body>
    <x xmlns="jabber:x:event">
        <offline/>
        <composing/>
    </x>
    <active xmlns="http://jabber.org/protocol/chatstates"></active>
    <stanza-id xmlns="urn:xmpp:sid:0" id="f1216887-bd44-46c4-9380-44d9f4dc84b8" by="muc2@conference.xmpp.localhost.example"></stanza-id>
    <addresses xmlns="http://jabber.org/protocol/address">
        <address type="ofrom" jid="user2@xmpp.localhost.example"/>
    </addresses>
</message>
```

**Comment by Fishbowler** [comment]
> Of more importance ... is the addressing in the other database columns. Are those consistent across the cluster?

Maybe not...?
image

The first row here has the users the wrong way round, right?

**Comment by Fishbowler** [comment]
Tested `conversation.database.use-openfire-tables` - this exhibits the same behaviour as before. Most messages are delivered for MAM requests for MUCs and personal requests, but PMs aren't retrieved.

Tested `conversation.roomArchiving.PMinPersonalArchive` and `conversation.roomArchiving.PMinRoomArchive`. With both enabled, it's possible for MAM queries to return both copies. With both disabled, PMs aren't ever stored to the Openfire database, and aren't returned for regular or full-text queries.

Testing "with" values return appropriate results, and return the same MAM results for a MUC regardless of whether a real JID or room JID is used.

**Comment by guusdk** [comment]
The inconsistent addressing is undesirable, as it might leak the 'real' JID of an occupant to the sender (that can retrieve the modified message from the archive). This issue is to be addressed in Openfire. See OF-2163 / https://github.com/igniterealtime/Openfire/pull/1770

**Comment by Fishbowler** [comment]
Performed further testing on semi-anonymous MUCs, the effect of upgrades on clients, archiving completely disabled, and another pass looking for any leaked personal info. Nothing untoward at all. With all previous issues resolved, this is ready to merge 👍

**Review by Fishbowler — APPROVED** [review]

**Pull request merged**
