### PR TITLE
fixes #235: Don't use deprecated Openfire methods

### LINKED ISSUE #235: Cannot use Monitoring on Openfire 4.8.0 snapshot
The current published version doesn't load. The current snapshot loads, but visiting /archive-settings.jsp gives the following error:

```
Exception:
java.lang.NoSuchMethodError: 'int org.jivesoftware.openfire.http.HttpBindManager.getHttpBindUnsecurePort()'
	at org.jivesoftware.openfire.plugin.monitoring.archiving_002dsettings_jsp._jspService(archiving_002dsettings_jsp.java:443)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:71)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.jivesoftware.openfire.container.PluginServlet.handleJSP(PluginServlet.java:462)
	at org.jivesoftware.openfire.container.PluginServlet.service(PluginServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

There were similar problems addressed in another plugin recently: https://github.com/igniterealtime/openfire-httpFileUpload-plugin/pull/34

### PR DESCRIPTION
**Pull request by Fishbowler**
Replace deprecated methods with the modern equivalents

### CODE REVIEW

**Comment by guusdk** [comment]
I've added commits that should make this work. Also added a changelog entry. Very basic testing didn't show any issues.

**Comment by guusdk** [comment]
I have [created a 2.3.1 release](https://github.com/igniterealtime/openfire-monitoring-plugin/pull/237) that explicitly defines a 'max' server version of 4.8.0. The changes in this PR should go 'after' that, in a release that is larger than 2.3.1.

**Comment by guusdk** [comment]
I've now rebased to main (which has the 2.3.1 release), and force-pushed to Fishbowler's branch.

**Comment by Fishbowler** [comment]
This appears to work, but needs some retesting around the JS libs. There's some problems in there, but not around this change. This, I think, is GTG for now.

**Pull request merged**
