### PR TITLE
Fixes #210 and #208

### LINKED ISSUE #210: Update Jersey dependency
We're using an old version of Jersey. As a result, we needed to pull in the Rome dependency. See https://github.com/igniterealtime/openfire-monitoring-plugin/commit/6a636a49c713c6e60dc1b767e5909f4215e8b312

The version of Rome that we're using has a known vulnerability. We could update it, but I'd rather update Jersey to no longer need Rome in the first place.

### PR DESCRIPTION
**Pull request by guusdk**
Note that the fix for #210 requires OF-2352 / https://github.com/igniterealtime/Openfire/pull/1945 which means that this PR will _not_ work with 4.7.0 beta (but hopefully will with 4.7.0 non-beta).

### CODE REVIEW

**Comment by Fishbowler** [comment]
Appears to "work" but seeing lots of instances of API misses on the plugin's pages. e.g.

GET http://xmpp1.localhost.example:9091/plugins/monitoring/api/buildprogress 404 (Not Found)

This also appears on master, but I considered that it might be an effect of Jersey API wiring?

**Comment by guusdk** [comment]
This will only work with Openfire master _after_ https://github.com/igniterealtime/Openfire/pull/1945 has been merged (which currently isn't the case). Can you retry with this Openfire branch: [guusdk:OF-2352_use-plugin-provided-servlet-context](https://github.com/guusdk/Openfire/tree/OF-2352_use-plugin-provided-servlet-context) (or: review/merge that PR)?

**Comment by Fishbowler** [comment]
Aw man, I didn't even check to see if it was merged :facepalm: 
Will do.

**Comment by Fishbowler** [comment]
Using a rebased version of this against a rebased version of OF-2352, the errors all disappear. Everything appears operation, except that I can't get Openfire to reliably recognise an active conversation. The users count goes up, but conversations regularly remains at 0. Suspect this might be related to which cluster node is senior.

**Comment by guusdk** [comment]
This issue is caused by the new to-and-from XML serialization that was put in by https://github.com/igniterealtime/openfire-monitoring-plugin/pull/209 (to fix #120 and #170). The `ConversationEvent` class does not serialize at all. This fact is hidden by the implementation (you're not seeing exceptions), which is why this isn't very obvious. The net result is that a junior node tries to send stuff to the senior cluster node, where that data never arrives.

**Comment by guusdk** [comment]
I've pushed a provisional change (I might want to clean this up a little), that should fix the problem. It seems to work for me.

**Comment by guusdk** [comment]
I've now pushed a more substantial fix, that also includes some unit tests that help verify the XML serialization bit. Should be good to go now.

**Comment by Fishbowler** [comment]
My observed problem no longer occurs, and still fixes both intended issues :+1:

**Review by Fishbowler — APPROVED** [review]

**Pull request merged**
