### PR TITLE
Evolution to make monitoring-plugin java11 compliant

### PR DESCRIPTION
**Pull request by B-apt**
see: https://github.com/igniterealtime/openfire-monitoring-plugin/issues/60

### CODE REVIEW

**Comment by guusdk** [comment]
Looks good to me! Can you please add this change to the changelog.html file that's also part of the code?

**Comment by B-apt** [comment]
@guusdk Done. Please could you squash those 2 commits when merging into Master ? Thanks :)

**Comment by guusdk** [comment]
Thanks! I think that squashing would remove you as an author from the commit? Maybe squash yourself (if you feel that's important - I don't really mind). If you're rewriting history, then it'd be good to include a reference to the issue number in your commit message title (makes for easier tracking down things in history)

I suggest:

> fixes #60: Evolution to make monitoring-plugin java11 compliant

If you include "fixes <number>" then Github will automatically close the issue when the PR is merged.  :)

**Comment by B-apt** [comment]
@guusdk done :)

**Comment by guusdk** [comment]
Awesome, thanks!

**Pull request merged**
