### PR TITLE
Add build config to get correct artifact names

### PR DESCRIPTION
**Pull request by Fishbowler**
Stolen from the example-plugin repo :)

Makes for easier dev workflow, but will it cause problems when publishing?

### CODE REVIEW

**Comment by guusdk** [comment]
I'm not strongly opposed, but haven't taken the time to look into this properly.

My primary concern is that this breaks consistency with other plugins. Also, I'm not quite sure if this would override another jar file of the same name (which isn't the Openfire plugin, but just the compiled source in jar format).

Without this, you'd only have to rename `target/monitoring-openfire-plugin-assembly.jar` to `target/monitoring.jar` right?

**Comment by Fishbowler** [comment]
> My primary concern is that this breaks consistency with other plugins.

I pinched this from the example plugin repo. Suspect existing plugins may be inconsistent with each other. 
I've checked the recently published "pade" and "ofmeet" - they are using this format, but "hazelcast" isn't.

> I'm not quite sure if this would override another jar file of the same name (which isn't the Openfire plugin, but just the compiled source in jar format).

Would this be likely?

> Without this, you'd only have to rename `target/monitoring-openfire-plugin-assembly.jar` to `target/monitoring.jar` right?

Yep.
Without this, would community members know to rename it? Is it just [this hint](https://github.com/igniterealtime/openfire-monitoring-plugin/blob/master/readme.html#L73)?

**Comment by guusdk** [comment]
>> I'm not quite sure if this would override another jar file of the same name (which isn't the Openfire plugin, but just the compiled source in jar format).
>
> Would this be likely?

Maybe - it closely matches the name for default archives, although that has a version number slapped on.

I'm not against this, I'm just dreading finding out what side-effects it has. :/

**Comment by akrherz** [comment]
repository has been rewritten, #128 covers this PR.

**Pull request closed without merging**
